### ISSUE TITLE
Parse song file name as "[Artist] - [Title]"

### ISSUE THREAD

**Issue by Keavon** [tarkah/karaoke-rs#10]
My collection has all songs in the form `Frank Sinatra - Fly Me To The Moon.mp3` and `Frank Sinatra - Fly Me To The Moon.cdg`. At the moment, all of these are being assigned a title of `Frank Sinatra - Fly Me To The Moon` and an artist of `<None>`. An option to parse the collection in `[Artist] - [Title]` format, or a user-templated format, would be excellent.

**Comment by tarkah** [comment]
Yeah I think it should just be a user-templated format. Currently it's looking for id3 tags, otherwise I'm using format "album - artist - song" since most my collection is that way.

**Comment by tarkah** [comment]
@Keavon, checkout #12 

I added some basic parsing logic. You can supply a user-defined format that best matches your collection. Here is the section I added to the config file about it:

```yaml
# Specify format of song title in collection. If no id3 tags are found, it will
# attempt to parse song name for title and artist using the following format.
#
# [Artist] and [Title] must be specifid. [*] can optionally be used as a catch all
# to specify all characters outside the artist and title. A deliminating character
# must be used between [Artist], [Title] and [*] tags.
#
# Default format is: "[*] - [Artist] - [Title]"
```

So you'd want to change is to `[Artist] - [Title]`
