### ISSUE TITLE
Web player websocket port and handshake issues

### ISSUE THREAD

**Issue by Keavon** [tarkah/karaoke-rs#17]
The web player keeps defaulting back to port `:9000` when accessed directly from its URL (or the page is reloaded):

1. Enable web player and set HTTP and websocket ports to different values
2. Open web player (I am using a domain name in my case, tunneling my computer with `ssh -R` to a Raspberry Pi server connected to a DNS entry).
3. Visit the web interface
4. Click the Player tab, then this works the first time (the dev tools Network tab shows the websocket connection is the newly chosen one)
5. Reload the player page, now the websocket connection is back to `:9000` and fails.
6. It appears every time `/player` is loaded directly, it requests `:9000` while every time it is accessed by clicking the Player tab, the port is correct.

The web player fails to establish a websocket connection when visiting the Player link a second time:
1. Visit the web interface home page and hard refresh (Ctrl Shift R)
2. Click the Player tab, the connection should be working and videos play
3. Hit the back button in the browser
4. The console shows this error and eventually the music for the currently queued karaoke video plays despite not even being on the player:
```
Uncaught TypeError: Cannot read property 'callback' of undefined
    at r (1.karaoke-rs.js:1)
    at Module.Ve (1.karaoke-rs.js:1)
    at __wbg_cargowebsnippetf5302c0143e9bd10d39262404fc2b4c9660c7f9d_645c5ca38dda53ac (karaoke-rs.js:1)
    at <yew::services::resize::ResizeTask as core::ops::drop::Drop>::drop::hf45e7f94856691f9 (:my-http-port/wasm-function[768]:0xbbe35)
    at core::ptr::real_drop_in_place::h76a109ebe0812206 (:my-http-port/wasm-function[673]:0xb2ce2)
    at <yew::html::scope::DestroyComponent<COMP> as yew::scheduler::Runnable>::run::h82153cfbd3015bc8 (:my-http-port/wasm-function[358]:0x823cd)
    at yew::scheduler::Scheduler::put_and_try_run::h654711681d8a2ef3 (:my-http-port/wasm-function[576]:0xa7e23)
    at yew::agent::AgentLink<AGN>::callback::{{closure}}::h164a1611c4638d27 (:my-http-port/wasm-function[860]:0xc32ba)
    at <stdweb::webcore::newtype::Newtype<(stdweb::webcore::serialization::FunctionTag, (A12,)),stdweb::webcore::mutfn::Mut<F>> as stdweb::webcore::serialization::FuncallAdapter<F>>::funcall_adapter::h3f17d9ef7d5dc8f9 (:my-http-port/wasm-function[243]:0x5aa58)
    at Object.n.STDWEB_PRIVATE.dyncall (1.karaoke-rs.js:1)
```
5. If you fool around with it enough, like remove the `/player` from the URL and hit enter, or reload the page on the home page, sometimes (often more consistently than other times) this error appears instead of the currently-queued video:
```
karaoke-rs.js:1 WebSocket connection to 'ws://my-domain:my-websocket-port/' failed: Connection closed before receiving a handshake response
```

**Comment by Keavon** [comment]
On a possibly related note, sometimes also I start up a song through the web player and the player interface remains on the splash screen (with the Karaoke RS logo) while the music plays in the background without the visuals. Checking the console, I see this error:

```
Uncaught (in promise) DOMException: Failed to set the 'buffer' property on 'AudioBufferSourceNode': Cannot set buffer to non-null after it has been already been set to a non-null buffer
    at Module.Vt (http://my-domain:my-port/1.karaoke-rs.js:1:18128)
    at __widl_f_set_buffer_AudioBufferSourceNode (http://my-domain:my-port/karaoke-rs.js:1:1338)
    at web_sys::AudioBufferSourceNode::set_buffer::ha7fe1411d4351eda (wasm-function[1490]:0xd6708)
    at <karaoke_rs_frontend::agents::player::PlayerAgent as yew::agent::Agent>::update::h96d4a29188285a95 (wasm-function[164]:0x1ac68)
    at <yew::agent::AgentEnvelope<AGN> as yew::scheduler::Runnable>::run::hd40fd22f603d4222 (wasm-function[226]:0x5151c)
    at yew::scheduler::Scheduler::put_and_try_run::h654711681d8a2ef3 (wasm-function[576]:0xa7e23)
    at yew::agent::AgentLink<AGN>::callback::{{closure}}::h73cac05766d2d009 (wasm-function[667]:0xb23e7)
    at <std::future::GenFuture<T> as core::future::future::Future>::poll::hc64c6ca62013a764 (wasm-function[543]:0xa38f1)
    at wasm_bindgen_futures::task::singlethread::Task::run::h3ed9cca7b8458010 (wasm-function[880]:0xc4803)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4ada5dc411afbfe2 (wasm-function[832]:0xc1103)
```

**Comment by tarkah** [comment]
So this is all a problem due to the "single page app" way the frontend is built with using [yew_router](https://github.com/yewstack/yew_router). When you go back a page, it's not actually requesting that previous page from the server, it's all handled within the wasm. I'm guessing the agent / worker that I am setting up when the `player` page loads isn't being dropped... and it's responsible over managing the websocket connection, playing the audio, computing the next cdg frame, etc.  I'd imagine if I can get the player component and related agent / worker to drop properly when you go "back" in the history api, it'll fix any issues with navigating away / back to that page.

As for the websocket port resetting to default, see the below snippet. I load the config from the server the first time the webpage is loaded / mounted.  Though it shouldn't "reset" after it has successfully grabbed that config data.  When you refresh the page, is there a GET request to `/api/config` and if so, is that failing or what is that returning? [https://github.com/tarkah/karaoke-rs/blob/819c620c98d862466e84ff123102d07bb2c63240/frontend/src/app.rs#L135-L144](https://github.com/tarkah/karaoke-rs/blob/819c620c98d862466e84ff123102d07bb2c63240/frontend/src/app.rs#L135-L144)

**Comment by Keavon** [comment]
Yes it is returning with `200 OK` and the response data is the well-formed JSON data which includes my ports and the other configuration details. But the websocket connection is the very first network request to show up in the list, while the config request is the very last. Perhaps it's just out of order.

**Comment by tarkah** [comment]
Got it, this will be an easy fix, I just need to hold off on creating the player component until that API request to `/api/config` resolve. There shouldn't be a fallback, because if it can't resolve against the server to get config info, it wouldn't be able to play anything anyways..

**Comment by tarkah** [comment]
> 
> 
> The web player fails to establish a websocket connection when visiting the Player link a second time:
> 
>     1. Visit the web interface home page and hard refresh (Ctrl Shift R)
> 
>     2. Click the Player tab, the connection should be working and videos play
> 
>     3. Hit the back button in the browser
> 
>     4. The console shows this error and eventually the music for the currently queued karaoke video plays despite not even being on the player:
> 
> 
> ```
> Uncaught TypeError: Cannot read property 'callback' of undefined
>     at r (1.karaoke-rs.js:1)
>     at Module.Ve (1.karaoke-rs.js:1)
>     at __wbg_cargowebsnippetf5302c0143e9bd10d39262404fc2b4c9660c7f9d_645c5ca38dda53ac (karaoke-rs.js:1)
>     at <yew::services::resize::ResizeTask as core::ops::drop::Drop>::drop::hf45e7f94856691f9 (:my-http-port/wasm-function[768]:0xbbe35)
>     at core::ptr::real_drop_in_place::h76a109ebe0812206 (:my-http-port/wasm-function[673]:0xb2ce2)
>     at <yew::html::scope::DestroyComponent<COMP> as yew::scheduler::Runnable>::run::h82153cfbd3015bc8 (:my-http-port/wasm-function[358]:0x823cd)
>     at yew::scheduler::Scheduler::put_and_try_run::h654711681d8a2ef3 (:my-http-port/wasm-function[576]:0xa7e23)
>     at yew::agent::AgentLink<AGN>::callback::{{closure}}::h164a1611c4638d27 (:my-http-port/wasm-function[860]:0xc32ba)
>     at <stdweb::webcore::newtype::Newtype<(stdweb::webcore::serialization::FunctionTag, (A12,)),stdweb::webcore::mutfn::Mut<F>> as stdweb::webcore::serialization::FuncallAdapter<F>>::funcall_adapter::h3f17d9ef7d5dc8f9 (:my-http-port/wasm-function[243]:0x5aa58)
>     at Object.n.STDWEB_PRIVATE.dyncall (1.karaoke-rs.js:1)
> ```

I'm getting this error too when I navigate away from `/player` using back. Appears to be the ResizeTask that I've created not dropping properly... Probably a bug I need to report over at [yew](https://github.com/yewstack/yew), but I'll try to play around with things to see if I can find a fix.

**Comment by tarkah** [comment]
https://github.com/tarkah/karaoke-rs/pull/18/commits/0b697d4ea6cd009ad85edcce61ba33fda2c88411 should fix the port issue

**Comment by tarkah** [comment]
> 
> 
> On a possibly related note, sometimes also I start up a song through the web player and the player interface remains on the splash screen (with the Karaoke RS logo) while the music plays in the background without the visuals. Checking the console, I see this error:
> 
> ```
> Uncaught (in promise) DOMException: Failed to set the 'buffer' property on 'AudioBufferSourceNode': Cannot set buffer to non-null after it has been already been set to a non-null buffer
>     at Module.Vt (http://my-domain:my-http-port/1.karaoke-rs.js:1:18128)
>     at __widl_f_set_buffer_AudioBufferSourceNode (http://my-domain:my-http-port/karaoke-rs.js:1:1338)
>     at web_sys::AudioBufferSourceNode::set_buffer::ha7fe1411d4351eda (wasm-function[1490]:0xd6708)
>     at <karaoke_rs_frontend::agents::player::PlayerAgent as yew::agent::Agent>::update::h96d4a29188285a95 (wasm-function[164]:0x1ac68)
>     at <yew::agent::AgentEnvelope<AGN> as yew::scheduler::Runnable>::run::hd40fd22f603d4222 (wasm-function[226]:0x5151c)
>     at yew::scheduler::Scheduler::put_and_try_run::h654711681d8a2ef3 (wasm-function[576]:0xa7e23)
>     at yew::agent::AgentLink<AGN>::callback::{{closure}}::h73cac05766d2d009 (wasm-function[667]:0xb23e7)
>     at <std::future::GenFuture<T> as core::future::future::Future>::poll::hc64c6ca62013a764 (wasm-function[543]:0xa38f1)
>     at wasm_bindgen_futures::task::singlethread::Task::run::h3ed9cca7b8458010 (wasm-function[880]:0xc4803)
>     at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4ada5dc411afbfe2 (wasm-function[832]:0xc1103)
> ```

For this issue, is it when you first load the page or after a song already plays and it goes into the next song / you trigger the next song with `play now` or `next` on the queue?

**Comment by Keavon** [comment]
> For this issue, is it when you first load the page or after a song already plays and it goes into the next song / you trigger the next song with `play now` or `next` on the queue?

Just after regularly playing several songs with the "Play" (not "Queue") button in the interface, probably (although I'm not 100% certain) after each song/video has already fully ended and returned to the splash screen.

**Comment by tarkah** [comment]
Hmmm, I drop the AudioBufferSourceNode at the end of each song, either ending naturally or force stopped by play now on a song, or next / stop on queue page. And then a new AudioBufferSourceNode is created before the new song is even fetched. Not sure where the gap would be where it's trying to add another song buffer to the node before it's dropped / a new one is created.

Can you try to recreate this when running in development mode `npm run start:dev` and send me the entire console log so I can see all the trace logging? Thanks!

**Comment by tarkah** [comment]
I forgot that I am forcing production mode even with `npm run start:dev` due to a bug, so you won't get any meaningful logging unless you update the library here...

https://github.com/tarkah/karaoke-rs/blob/819c620c98d862466e84ff123102d07bb2c63240/frontend/src/lib.rs#L21-L29

Pass `Level::Trace` into the init... `web_logger::custom_init(Level::Trace);`

**Comment by tarkah** [comment]
I posted https://github.com/yewstack/yew/issues/904 for the resize task causing a panic...

**Comment by Keavon** [comment]
Cool! I will try and test these things for you in the next few days, quite busy tonight though.

**Comment by tarkah** [comment]
No rush! I'm pretty busy as well. Appreciate you uncovering all this!

**Comment by tarkah** [comment]
Good news, after I merge https://github.com/tarkah/karaoke-rs/pull/19, this should fully fix all issues related to navigating away from the `player` page. If you click back, the audio will end properly and the page you were previously on will render properly.

No idea if any of this will fix the issue around the below error, but if not, it should be the ONLY error left related to this issue

```
Uncaught (in promise) DOMException: Failed to set the 'buffer' property on 'AudioBufferSourceNode': Cannot set buffer to non-null after it has been already been set to a non-null buffer
```

**Comment by tarkah** [comment]
@Keavon please try the newest release, 0.9.1 and see if any of these issues still exist. Thanks!

**Comment by Keavon** [comment]
@tarkah I downloaded 0.9.1 and I am getting [this error](https://files.keavon.com/-/PowderbluePlaintiveChimneyswift/capture.png) when I open the Player page. I also see `[2020-02-07T08:52:26Z INFO  karaoke_rs::websocket] Connection from 127.0.0.1:63241` show up in the karaoke-rs console and `[2020-02-07T08:52:26Z INFO  karaoke_rs::websocket] Connection from 127.0.0.1:63241` when closing the browser page. The web player is entirely nonfunctional because of this error.

**Comment by tarkah** [comment]
Huh, does it do this for all your songs, or just a specific song? I'll try to fix it so the program doesn't panic and the web page is still usable. If it can't decode your mp3 file, I'm not sure why that'd be.

Sorry for all these errors, I'm not experiencing any of them. Appreciate you uncovering them all!

**Comment by tarkah** [comment]
@Keavon #20 should do the trick. The player will no longer panic, however it will obviously not play the song because it can't decode that audio file. A WARN will be logged to console notifying the user to remove that song from the queue. Since no panic occurs, you can easily backspace -> Queue page, hit next song, then go back to player (or have queue open on another tab / device)
