### ISSUE TITLE
Chrome requires user gesture to start audio context

### ISSUE THREAD

**Issue by Keavon** [tarkah/karaoke-rs#22]
Unfortunately there's some edge cases like this one we have to deal with...

```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
```

(Start the program in web mode, open a window for the player and a window to start a song, hit play on a song, after a few seconds the song loads and the screen goes black with this in the console.)

**Comment by tarkah** [comment]
Yeah I'm aware of this one... There really is no way around it that isn't ridiculously hacky that I could find. You'll just have to load the index page first, then click on the player link in the header. Loading the player page directly doesn't give you time to interact with the page, preventing the audio from automatically playing.

**Comment by tarkah** [comment]
If you do load the player page directly, you can click on the background very fast and it'll register as an interaction and everything will work fine.

**Comment by tarkah** [comment]
Firefox doesn't have this restriction

**Comment by Keavon** [comment]
It's not pretty but I would suggest adding a graceful handling of this that adds a button to "load" the player when necessary.

**Comment by tarkah** [comment]
Hmmm, I'll have to think about this. It'd be easy to add, but navigating to the page by clicking the link in the header already circumvents this problem. And for browsers like Firefox where this isn't an issue, the extra button would be pointless.

At the same time though, it's undefined behavior that may trip people up even if it's documented somewhere to always navigate through the link.

**Comment by tarkah** [comment]
I guess I can only create the button in scenarios where this is an issue (check if AudioContext is in a suspended state after being created). So I'll definitely add this and make it only appear when applicable.

**Comment by Keavon** [comment]
Detecting the problem when it does show up and dealing with it, instead of leaving a black screen and having to check the console, would definitely be the best user experience!

**Comment by tarkah** [comment]
Agreed! I'll look into this over the next few days. Thanks for opening this!

**Comment by tarkah** [comment]
@Keavon, see #23.  

It creates the following modal, only if AudioContext is suspended due to the above problem. Once closed, song playback will resume appropriately. Any recommendations on what the message should say, or if it should be displayed / styled differently would be appreciated.

![image](https://user-images.githubusercontent.com/10239377/75180619-6d5add80-56f1-11ea-815b-3de206e62360.png)

**Comment by Keavon** [comment]
Here's a couple options for text and [button] names.

* "Ready to load player. [Begin]"
* "Get ready for some karaoke! [Load Player]"

For styling, maybe keep it centered at 50% horizontally and vertically, give it some rounded corners, a single line of text with the button to the right or maybe below the text, and a color theme that fits the beautiful background imagery/logo (perhaps a border or box-shadow that fits with the look of the neon tubes).

**Comment by tarkah** [comment]
Awesome suggestions, thanks!

**Comment by tarkah** [comment]
How's this?

![image](https://user-images.githubusercontent.com/10239377/75191038-730eee00-5706-11ea-8928-33d24f3228a0.png)

**Comment by tarkah** [comment]
I think I like this message better :P

![image](https://user-images.githubusercontent.com/10239377/75191635-8ec6c400-5707-11ea-8d2e-508a26b47add.png)

**Comment by Keavon** [comment]
The second iteration looks much nicer! I'd still suggest a thicker outline (like the thickness of the neon tubes) and maybe a more rounded outer border. And see if it's possible to add the glow (pink shadow) on the inside too with https://css-tricks.com/snippets/css/css-box-shadow/

**Comment by tarkah** [comment]
Ahh, I see what you're going for :)

**Comment by tarkah** [comment]
Getting closer...

![image](https://user-images.githubusercontent.com/10239377/75197943-48c42d00-5714-11ea-857d-68bfa500e753.png)

**Comment by Keavon** [comment]
Nice! Maybe shrink the width of the shadow and make it more transparent so emphasize the solid border but just give it a subtle glow.

**Comment by tarkah** [comment]
Think I finally landed on something I like

![chrome_nlxvKxdcfJ](https://user-images.githubusercontent.com/10239377/75201033-3a7a0f00-571c-11ea-90ef-5fa673cf1b75.png)

**Comment by Keavon** [comment]
Lovely! Final small suggestion, make the button text larger and maybe see also if bolding the button text looks nicer.

**Comment by tarkah** [comment]
Good call, thanks for the help!

![image002](https://user-images.githubusercontent.com/10239377/75201445-4adeb980-571d-11ea-8ce9-f6129fbd9c18.png)
