### ISSUE TITLE
Option to display video scaled to full screen size without color-changing background

### ISSUE THREAD

**Issue by Keavon** [tarkah/karaoke-rs#7]
The video player is sometimes quite small and the color-changing background could be distracting in some situations. An option to scale the video to the full screen size would be great, and even better if we could optionally keep the color-changing background but scale the video to some percent of the window size.

**Comment by tarkah** [comment]
Yeah! I can definitely add these options.

The video is currently scaled at 1.5x. So I can add an option to specify scale and also set it to full screen dimensions. I'll add an option to disable the background, so it'll just be black.

**Comment by Keavon** [comment]
That sounds wonderful! If one of those scaling options can be "100%" or something like that, so we don't have to guess what scale factor fits the screen, that would be great. Or even better: if scaling can represented as either some factor times the default video size (like `1.5x` or `3x`) or some percentage of the fullscreen size (like `100%` for fullscreen or `75%`). Thank you!

**Comment by tarkah** [comment]
I was thinking of two different options, one for video scale (2x) and another which is just a flag for fullscreen which would take precedent if chosen.

I'm thinking these video player customizations should be exposed as a settings page on the website.

**Comment by tarkah** [comment]
No problem! It's good to get feedback from someone. Hope you're liking the program!

**Comment by Keavon** [comment]
I am! I really appreciate your attention to design. That is something so many other programs lack. I will keep playing around with it and opening more issues with additional feedback. Thank you for making this!

**Comment by tarkah** [comment]
Thank you. Awesome! Bring them on. I just released a new feature to play songs in the browser, so you can easily use it remotely or pull it up on your phone browser.

**Comment by Keavon** [comment]
I am planning to use that feature to turn my Raspberry Pi server into a karaoke server, which also makes it easy for guests to visit on their phones if I bind that to a DNS record on my website.

**Comment by tarkah** [comment]
That's exactly why I did it! I've got it setup on my raspberry pi 3b+ and it works great!

**Comment by tarkah** [comment]
@Keavon check out #15 

You can supply the following options in the config file:
```yaml
# Settings to customize look of the player
#
#player:

  # Set lyrics to fit entire screen
  #fullscreen: false
  
  # Scale lyrics by this factor, default is 1.5
  #scale: 1.5

  # Disables the rainbow background. Will be black instead.
  #disable_background: false

```

**Comment by tarkah** [comment]
I added #16, for now these settings have to be specified in the config file.

Let me know if all the enhancements I made today worked out for you!

**Comment by Keavon** [comment]
One small pitfall I hit that might confuse other users: I uncommented `fullscreen: false` and set it to `true` but I didn't first uncomment `player:` and this caused an error reading the YAML file (which makes sense but might confuse others). Perhaps all the defaults should start uncommented, but with their current default values?

**Comment by tarkah** [comment]
Yeah that's exactly what needs to happen. I noticed this last night, too.
